name: Docker-build

on:
  push:
    branches: [master]

jobs:
  docker-build:
    runs-on: ubuntu-18.04
    env:
      DOCKER_IMAGE_NAME: original-covid-app-container
      REACT_APP_WORLD_HOST: ${{ secrets.REACT_APP_WORLD_HOST }}
      REACT_APP_PREFECTURE_HOST: ${{ secrets.REACT_APP_PREFECTURE_HOST }}
    steps:
      - name: Check out source code
        uses: actions/checkout@v1

      - name: Build and push docker image
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKER_REGISTRY }}/${DOCKER_IMAGE_NAME}:latest
          echo "Docker image: ${DOCKER_IMAGE}"
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
          docker build -t $DOCKER_IMAGE -f Dockerfile.prod . \
            --build-arg WORLD_HOST=${REACT_APP_WORLD_HOST}
            --build-arg PREFECTURE_HOST=${REACT_APP_PREFECTURE_HOST} \
          docker push $DOCKER_IMAGE